# Generated by Django 6.1 on 2026-08-31 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curricula', to='core.department'),
        ),
        migrations.AlterField(
            model_name='curriculumsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_subjects', to='core.subject'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='core.faculty'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculties', to='core.university'),
        ),
        migrations.AlterField(
            model_name='openclass',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='open_classes', to='core.subject'),
        ),
        migrations.AlterField(
            model_name='section',
            name='open_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='core.openclass'),
        ),
        migrations.AlterField(
            model_name='student',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.curriculum'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='core.department'),
        ),
    ]
